### ISSUE TITLE
Every prediction fails on Replicate

### ISSUE THREAD

**Issue by cristianvogel** [Dabble-Studio/3d-to-photo#1]
...for me. 

I have the setup and env config working correctly, but every attempt fails at the https://replicate.com/andreasjansson/stable-diffusion-inpainting checkpoint

**Comment by nmathew87** [comment]
Could you share the error log? Just some checks
- did you run the image proc server
- can you see the prediction started on replicate?

**Comment by nmathew87** [comment]
the issue seems to have been a replicate issue and has resolved itself. Could you confirm and i'll close the issue.

**Comment by nmathew87** [comment]
closing for now as it seems a duplicate of this. But can reopen if issue persists
https://github.com/Dabble-Studio/3d-to-photo/issues/2
