### ISSUE TITLE
All predictions fail on replicate 

### ISSUE THREAD

**Issue by Sangrail** [Dabble-Studio/3d-to-photo#2]
Cloned and setup local as directed.

- image_proc_server is running
- nextjs app running

<img width="1251" alt="Screenshot 2023-10-20 at 12 43 58" src="https://github.com/Dabble-Studio/3d-to-photo/assets/7015121/0ad04ab4-8024-427d-bf70-3009fde6e695">

I get the following message: 
<img width="737" alt="Screenshot 2023-10-20 at 12 42 06" src="https://github.com/Dabble-Studio/3d-to-photo/assets/7015121/cab01f32-4794-4565-a50f-3af6f9376f10">

Maybe the issue is an omission in documentation? Do I need to do anything with Replicate?

**Comment by nmathew87** [comment]
ah ok perfect. seems like it was a replicate issue! thanks for checking again!
